version: "3"

services:
    bot:
        build: .
        command: python camila.py
        restart: always
        volumes:
            - .:/src
            - supercamila:/src/data

volumes:
    supercamila:
